Bluetooth: btmtk: Fix btmtk.c undefined reference build error
ANBZ: #41994

commit f0c83a23fcbb424fdff5b38fbcdda3c04003a210 upstream.

commit ade787f04790654849d20cd0706644ba51589aa5 stable.

MediaTek moved some usb interface related function to btmtk.c which
may cause build failed if BT USB Kconfig wasn't enabled.
Fix undefined reference by adding config check.

btmtk.c:(.text+0x89c): undefined reference to `usb_alloc_urb'
btmtk.c:(.text+0x8e3): undefined reference to `usb_free_urb'
btmtk.c:(.text+0x956): undefined reference to `usb_free_urb'
btmtk.c:(.text+0xa0e): undefined reference to `usb_anchor_urb'
btmtk.c:(.text+0xb43): undefined reference to `usb_autopm_get_interface'
btmtk.c:(.text+0xb7e): undefined reference to `usb_autopm_put_interface'
btmtk.c:(.text+0xf70): undefined reference to `usb_disable_autosuspend'
btmtk.c:(.text+0x133a): undefined reference to `usb_control_msg'

[backport-note]
PatchPilot-Conflict-Type: context_drift, missing_prereq
PatchPilot-Conflict-Files: drivers/bluetooth/btmtk.c, drivers/bluetooth/btmtk.h
PatchPilot-Resolution:
  drivers/bluetooth/btmtk.c: Close CONFIG_BT_HCIBTUSB_MTK guard after downstream's only USB export
  drivers/bluetooth/btmtk.h: Wrap downstream's only USB decl in new CONFIG_BT_HCIBTUSB_MTK guard

Fixes: d019930b0049 ("Bluetooth: btmtk: move btusb_mtk_hci_wmt_sync to btmtk.c")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202407091928.AH0aGZnx-lkp@intel.com/
Signed-off-by: Chris Lu <chris.lu@mediatek.com>
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Assisted-by: PatchPilot <patchpilot@openanolis.org>
Signed-off-by: Dust Li <dust.li@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/11719