seqlock: Allow UBSAN_ALIGNMENT to fail optimizing
ANBZ: #45599

commit 88331c4ec23a28c1006ec532fa64763d4c695e90 upstream.

commit 1f140d2953901f693ae2e871b74afe5612c942b8 stable.

With gcc-15 and gcc-16 with UBSAN_ALIGNMENT enabled the compiler fails to
inline and optimize __scoped_seqlock_bug() away on s390:

s390x-16.1.0-ld: kernel/sched/build_policy.o: in function `__scoped_seqlock_next':
/.../seqlock.h:1286:(.text+0x22030): undefined reference to `__scoped_seqlock_bug'

Fix this by adding UBSAN_ALIGNMENT to the list of config options where a
not inlined empty __scoped_seqlock_bug() is allowed.

Closes: https://lore.kernel.org/r/20260515092057.810542-1-arnd@kernel.org/
Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
Link: https://patch.msgid.link/20260519110315.1385307-1-hca@linux.ibm.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Assisted-by: PatchPilot <patchpilot@openanolis.org>
Signed-off-by: Peng Wang <rocking@linux.alibaba.com>
Acked-by: Peng Wang <peng_wang@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/13445