Bluetooth: btmtk: Fix btmtk.c undefined reference build error harder
ANBZ: #41994

Bluetooth: btmtk: Fix btmtk.c undefined reference build error harder

commit 61f7a8f975456d7be21100ee0936389142b95a81 upstream.

commit 88a04d42aa6c0c1b22d90f7def65ba9d7c65254d stable.

The previous fix was incomplete as the link failure still persists
with CONFIG_USB=m when the sdio or serial wrappers for btmtk.c
are build-in:

btmtk.c:(.text+0x468): undefined reference to `usb_alloc_urb'
btmtk.c:(.text+0x488): undefined reference to `usb_free_urb'
btmtk.c:(.text+0x500): undefined reference to `usb_anchor_urb'
btmtk.c:(.text+0x50a): undefined reference to `usb_submit_urb'
btmtk.c:(.text+0x92c): undefined reference to `usb_control_msg'
btmtk.c:(.text+0xa92): undefined reference to `usb_unanchor_urb'
btmtk.c:(.text+0x11e4): undefined reference to `usb_set_interface'
btmtk.c:(.text+0x120a): undefined reference to `usb_kill_anchored_urbs'

Disallow this configuration.

Fixes: f0c83a23fcbb ("Bluetooth: btmtk: Fix btmtk.c undefined reference build error")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Assisted-by: PatchPilot <patchpilot@openanolis.org>
Signed-off-by: Dust Li <dust.li@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/12967