x86: Restrict KVM-induced symbol exports to KVM modules where obvious/possible
ANBZ: #40036

commit 6276c67f2bc4aeaf350a7cf889c33c38b3330ea9 upstream.

Extend KVM's export macro framework to provide EXPORT_SYMBOL_FOR_KVM(),
and use the helper macro to export symbols for KVM throughout x86 if and
only if KVM will build one or more modules, and only for those modules.

To avoid unnecessary exports when CONFIG_KVM=m but kvm.ko will not be
built (because no vendor modules are selected), let arch code #define
EXPORT_SYMBOL_FOR_KVM to suppress/override the exports.

Note, the set of symbols to restrict to KVM was generated by manual search
and audit; any "misses" are due to human error, not some grand plan.

[ backport ]
Don`t export EXPORT_SYMBO_FOR_KVM(wbinvd_on_all_cpus), since there are some
other dirver used it.
ERROR: modpost: module drm uses symbol wbinvd_on_all_cpus from namespace module:kvm,kvm-amd,kvm-intel, but does not import it.
ERROR: modpost: module i915 uses symbol wbinvd_on_all_cpus from namespace module:kvm,kvm-amd,kvm-intel, but does not import it.

Intel-SIG: commit 6276c67f2bc4 x86: Restrict KVM-induced symbol exports to KVM modules where obvious/possible

Signed-off-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
Acked-by: Kai Huang <kai.huang@intel.com>
Tested-by: Kai Huang <kai.huang@intel.com>
Link: https://patch.msgid.link/20251112173944.1380633-5-seanjc%40google.com
[ Jun Miao: amend commit log ]
Signed-off-by: Jun Miao <jun.miao@intel.com>
Reviewed-by: Jiaqi Gao <jiaqi.gao@linux.alibaba.com>
Reviewed-by: Qinyun Tan <qinyuntan@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/13233