modpost: check forbidden MODULE_IMPORT_NS("module:") at compile time
ANBZ: #40036

commit 9c036cfbb75bb58ecce589f547fdb8af153493a6 upstream.

Explicitly adding MODULE_IMPORT_NS("module:...") is not allowed.

Currently, this is only checked at run time. That is, when such a
module is loaded, an error message like the following is shown:

  foo: module tries to import module namespace: module:bar

Obviously, checking this at compile time improves usability.

In such a case, modpost will report the following error at compile time:

  ERROR: modpost: foo: explicitly importing namespace "module:bar" is not allowed.

Intel-SIG: commit 9c036cfbb75b modpost: check forbidden MODULE_IMPORT_NS("module:") at compile time

Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
[ Jun Miao: amend commit log ]
Signed-off-by: Jun Miao <jun.miao@intel.com>
Reviewed-by: Jiaqi Gao <jiaqi.gao@linux.alibaba.com>
Reviewed-by: Qinyun Tan <qinyuntan@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/13233