crypto: qat - add missing header inclusion
ANBZ: #21972

commit 61fc01f8f7f8e299b9fed5a5e5e068ef0e40593d upstream.

Without this header, the build of the new qat_6xxx driver fails when
CONFIG_PCI_IOV is not set:

    In file included from drivers/crypto/intel/qat/qat_common/adf_gen6_shared.c:7:
    drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h: In function 'adf_gen4_init_pf_pfvf_ops':
    drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h:13:34: error: 'adf_pfvf_comms_disabled' undeclared (first use in this function)
       13 |         pfvf_ops->enable_comms = adf_pfvf_comms_disabled;
          |                                  ^~~~~~~~~~~~~~~~~~~~~~~

Intel-SIG: commit 61fc01f8f7f8 crypto: qat - add missing header inclusion
Backport to fix Intel QAT driver from v6.16 to v6.19

Fixes: 17fd7514ae68 ("crypto: qat - add qat_6xxx driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
[ Liang Fang: amend commit log ]
Signed-off-by: Liang Fang <liang.a.fang@intel.com>
Reviewed-by: Zhengyong Wang <zhengyong_wzy@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/8302